# Generated by Django 4.1.3 on 2022-11-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_categor_post_catogory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categor',
            new_name='Category',
        ),
    ]
