# Generated by Django 4.1.3 on 2022-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_categor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catogory',
            new_name='category',
        ),
    ]
